version: "3.4"

services:
    php:
        image: ${IMAGES_PREFIX:-}app-php
        restart: unless-stopped
        volumes:
            - php_socket:/var/run/php
        environment:
            LARAVEL_VERSION: ${LARAVEL_VERSION:-10}
            STABILITY: ${STABILITY:-stable}

    nginx:
        image: ${IMAGES_PREFIX:-}app-nginx
        depends_on:
            php:
                condition: service_healthy
                restart: true
        environment:
            SERVER_NAME: ${SERVER_NAME:-localhost}
        restart: unless-stopped
        volumes:
            - php_socket:/var/run/php
        ports:
            # HTTP
            -   target: 80
                published: ${HTTP_PORT:-80}
                protocol: tcp
            # HTTPS
            -   target: 443
                published: ${HTTPS_PORT:-443}
                protocol: tcp

volumes:
    php_socket:
